AllCops:
  NewCops: enable

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-internal_affairs
  - rubocop-dobado_architecture

Naming/FileName:
  Exclude:
    - lib/rubocop-dobado_architecture.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
