# Write it!

Dobado/ControllerRecommendRestfulMethods:
  Description: "コントローラーのアクション名として、RESTfulなメソッド名を推奨する"
  Enabled: true
  VersionAdded: "0.1.0"
  RecommendedMethods:
    - index
    - show
    - new
    - edit
    - create
    - update
    - destroy
  Include:
    - "app/controllers/**/*.rb"

Dobado/ModelMail:
  Description: "モデル内でメール送信を行うのを非推奨とする"
  Enabled: true
  VersionAdded: "0.1.0"
  Include:
    - "app/models/**/*.rb"
